"""add_fee_tables

Revision ID: 80e678e503d6
Revises: 004_profile_photo
Create Date: 2026-03-06 11:57:50.737579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = '80e678e503d6'
down_revision: Union[str, None] = '004_profile_photo'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())

    if 'fee_structures' not in tables:
        op.create_table(
            'fee_structures',
            sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('student_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('branch_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('advance_fees', sa.Float(), nullable=True),
            sa.Column('term_fee_1', sa.Float(), nullable=True),
            sa.Column('term_fee_2', sa.Float(), nullable=True),
            sa.Column('term_fee_3', sa.Float(), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['branch_id'], ['branches.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('student_id')
        )

    if 'fee_payments' not in tables:
        op.create_table(
            'fee_payments',
            sa.Column('id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('fee_structure_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('student_id', postgresql.UUID(as_uuid=True), nullable=False),
            sa.Column('component', sa.String(length=50), nullable=False),
            sa.Column('amount_paid', sa.Float(), nullable=False),
            sa.Column('payment_mode', sa.String(length=50), nullable=False),
            sa.Column('payment_date', sa.DateTime(), nullable=True),
            sa.Column('marked_by', postgresql.UUID(as_uuid=True), nullable=True),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('updated_at', sa.DateTime(), nullable=True),
            sa.ForeignKeyConstraint(['fee_structure_id'], ['fee_structures.id'], ondelete='CASCADE'),
            sa.ForeignKeyConstraint(['marked_by'], ['users.id'], ondelete='SET NULL'),
            sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
            sa.PrimaryKeyConstraint('id')
        )

    branch_indexes = {idx['name'] for idx in inspector.get_indexes('branches')}
    branch_code_idx = op.f('ix_branches_code')
    if branch_code_idx not in branch_indexes:
        op.create_index(branch_code_idx, 'branches', ['code'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = set(inspector.get_table_names())

    branch_indexes = {idx['name'] for idx in inspector.get_indexes('branches')}
    branch_code_idx = op.f('ix_branches_code')
    if branch_code_idx in branch_indexes:
        op.drop_index(branch_code_idx, table_name='branches')

    if 'fee_payments' in tables:
        op.drop_table('fee_payments')
    if 'fee_structures' in tables:
        op.drop_table('fee_structures')
    # ### end Alembic commands ###
